### ISSUE TITLE
Mapbox Customize Markers In iOS with UIView

### ISSUE THREAD

**Issue by heliumsoule** [incanus/ama#10]
Hey Justin,

I want to use Mapbox on an iOS application. However, because I'm displaying text and don't want to lose the resolution on my markers, I want to use UIViews instead of UIImages. I read somewhere that Mapbox is looking to add that feature in the future. Can you tell me how when that will be available? Thanks!

P.S. Happy New Years

Sincerely,
Hsoule.

**Comment by incanus** [comment]
The main issue for tracking this feature is at https://github.com/mapbox/mapbox-gl-native/issues/1784, and I've done the most research into its feasibility for iOS (see https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-117471812; building the right foundation for animations is the tricky part here). 

I don't have any update on the ETA right now, as Mapbox is on break this week and I myself am away from work for a while for some personal matters. Stay tuned though!

**Comment by incanus** [comment]
Also, digging deeper: if you are using static images, you shouldn't be losing any resolution. If you are creating imagery on the fly, are you sure that your `CGContext` matches the `UIScreen` scale?

**Comment by heliumsoule** [comment]
Thanks for responding Incanus. I need to display customized map markers whose text can change. So I am taking creating a picture of the UIView and then exporting that as an image on top of the map. I'm going to try matching the CGContext and UIScreen scale. Thank you for the help.
