### ISSUE TITLE
What games do you play?

### ISSUE THREAD

**Issue by arthurvr** [incanus/ama#2]
Video games, board games, card games, ...

**Comment by incanus** [comment]
I don't do too much video gaming these days, but every now and then, I'll go back to the classics, which for me is NES, SNES, and sometimes a bit of Wii Mario and Zelda. I played World of Warcraft for a number of years from its beginning, but had to make more room in my life for other things. I still miss it. 

I'm more into board, card, & tabletop games. Card games I own and which are my faves are Guillotine, Loot, Archaeology, Love Letters, and Jaipur. 

Board games include Pandemic, Lords of Waterdeep, The Ten Days series (America, Europe, World), and Dominion. I have some old (late 70s/early 80s) games by the now-defunct Avalon Hill Company including Dune, Gettysburg, and my favorite-yet-most-difficult game of all time, Magic Realm. 

Fun question! Thanks @arthurvr.
