### ISSUE TITLE
Mapbox mobile offline capability

### ISSUE THREAD

**Issue by Arman92** [incanus/ama#6]
Hello Justin,

I was wondering when will Mapbox mobile (Android) will support offline maps? 

can you give me an approximate time?

Thanks

**Comment by incanus** [comment]
Hi @Arman92. We are currently on track for offline capability in the mobile toolkits sometime in January. The best place to follow the overall work is https://github.com/mapbox/mapbox-gl-native/issues/584, and in particular, I have been working on some early tests and underpinnings in https://github.com/mapbox/mapbox-gl-native/issues/2939 Stay tuned!

**Comment by Arman92** [comment]
Hi Justin,

I'm eager to test the offline maps with Mapbox, any updates?
