### ISSUE TITLE
Did you have a nice christmas?

### ISSUE THREAD

**Issue by robbbz** [incanus/ama#9]

**Comment by incanus** [comment]
Hi @robbbz. You'd have no way of knowing this (so no worries), but Christmas this year was pretty difficult. My wife has been diagnosed with rare cancer in December after first symptoms in November. See http://standstrongwith.us for more info. 

The one thing that stayed the same was that we don't typically travel during December holidays, holing up at home and enjoying avoiding airports (unlike the rest of the year, when we travel a lot). So it was nice and less stressful to continue that this year. 

Hope you are having a great holiday season! :christmas_tree:
